# To use:
#
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate aehmc-dev
#
name: aehmc-dev
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - compilers
  - numpy>=1.18.1
  - scipy>=1.4.0
  - aesara>=2.8.3
  - aeppl>=0.0.40
  # Intel BLAS
  - mkl
  - mkl-service
  - libblas=*=*mkl
  # For testing
  - pytest
  - coverage>=5.1
  - coveralls
  - pytest-cov
  - pytest-xdist
  # For building docs
  - sphinx>=1.3
  - sphinx_rtd_theme
  - pygments
  - pydot
  - ipython
  # developer tools
  - pre-commit
  - packaging
  - typing_extensions
